/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./index.html', './frontend/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Chrome-like color palette
                chrome: {
                    bg: 'var(--chrome-bg)',
                    surface: 'var(--chrome-surface)',
                    'surface-solid': 'var(--chrome-surface-solid)',
                    'surface-hover': 'var(--chrome-surface-hover)',
                    'surface-active': 'var(--chrome-surface-active)',
                    border: 'var(--chrome-border)',
                    text: 'var(--chrome-text)',
                    'text-secondary': 'var(--chrome-text-secondary)',
                    'text-muted': 'var(--chrome-text-muted)',
                    accent: 'var(--chrome-accent)',
                    'accent-hover': 'var(--chrome-accent-hover)',
                },
                agent: {
                    primary: 'var(--agent-primary)',
                    secondary: 'var(--agent-secondary)',
                    success: 'var(--agent-success)',
                    warning: 'var(--agent-warning)',
                    error: 'var(--agent-error)',
                },
                // MD3 aliases mapped to Chrome theme to support Stitch designs
                'background': 'var(--chrome-bg)',
                'surface': 'var(--chrome-bg)',
                'surface-container-lowest': 'var(--chrome-surface-solid)',
                'surface-container-low': 'var(--chrome-surface-soft)',
                'surface-container': 'var(--chrome-surface)',
                'surface-container-high': 'var(--chrome-surface-strong)',
                'surface-container-highest': 'var(--chrome-border)',
                'surface-variant': 'var(--chrome-surface-hover)',
                'on-surface': 'var(--chrome-text)',
                'on-surface-variant': 'var(--chrome-text-secondary)',
                'primary': 'var(--chrome-accent)',
                'on-primary': '#ffffff',
                'primary-container': 'var(--chrome-accent-light)',
                'on-primary-container': 'var(--chrome-accent-hover)',
                'error': 'var(--agent-error)',
            },
            fontSize: {
                '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
                'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
                'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
                'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
                'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
                'display': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
                mono: ['JetBrains Mono', 'Consolas', 'monospace'],
                'label-sm': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'title-lg': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'display': ['Inter', 'sans-serif'],
            },
            spacing: {
                chrome: '8px',
                'chrome-sm': '4px',
                'chrome-lg': '12px',
                gutter: '20px',
                'margin-mobile': '16px',
                'margin-desktop': '32px',
                unit: '4px',
                'stack-gap': '12px',
                agent_panel_width: '320px',
                sidebar_width: '260px',
            },
            borderRadius: {
                chrome: '8px',
                'chrome-sm': '4px',
                'chrome-lg': '12px',
                'chrome-full': '9999px',
            },
            boxShadow: {
                chrome: '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.06)',
                'chrome-lg': '0 4px 6px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.06)',
                'chrome-xl': '0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05)',
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'fade-in': 'fadeIn 0.2s ease-out',
                'slide-up': 'slideUp 0.2s ease-out',
                'slide-down': 'slideDown 0.2s ease-out',
                'scale-in': 'scaleIn 0.15s ease-out',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { opacity: '0', transform: 'translateY(-10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.95)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
            },
            transitionDuration: {
                chrome: '150ms',
            },
            backdropBlur: {
                chrome: '20px',
            },
        },
    },
    plugins: [],
};
